export const phoneCountries = [
  { flag: "🇦🇪", label: "United Arab Emirates", dialCode: "+971" },
  { flag: "🇦🇫", label: "Afghanistan", dialCode: "+93" },
  { flag: "🇦🇱", label: "Albania", dialCode: "+355" },
  { flag: "🇩🇿", label: "Algeria", dialCode: "+213" },
  { flag: "🇦🇸", label: "American Samoa", dialCode: "+1684" },
  { flag: "🇦🇩", label: "Andorra", dialCode: "+376" },
  { flag: "🇦🇴", label: "Angola", dialCode: "+244" },
  { flag: "🇦🇮", label: "Anguilla", dialCode: "+1264" },
  { flag: "🇦🇬", label: "Antigua and Barbuda", dialCode: "+1268" },
  { flag: "🇦🇷", label: "Argentina", dialCode: "+54" },
  { flag: "🇦🇲", label: "Armenia", dialCode: "+374" },
  { flag: "🇦🇼", label: "Aruba", dialCode: "+297" },
  { flag: "🇦🇺", label: "Australia", dialCode: "+61" },
  { flag: "🇦🇹", label: "Austria", dialCode: "+43" },
  { flag: "🇦🇿", label: "Azerbaijan", dialCode: "+994" },
  { flag: "🇧🇸", label: "Bahamas", dialCode: "+1242" },
  { flag: "🇧🇭", label: "Bahrain", dialCode: "+973" },
  { flag: "🇧🇩", label: "Bangladesh", dialCode: "+880" },
  { flag: "🇧🇧", label: "Barbados", dialCode: "+1246" },
  { flag: "🇧🇾", label: "Belarus", dialCode: "+375" },
  { flag: "🇧🇪", label: "Belgium", dialCode: "+32" },
  { flag: "🇧🇿", label: "Belize", dialCode: "+501" },
  { flag: "🇧🇯", label: "Benin", dialCode: "+229" },
  { flag: "🇧🇲", label: "Bermuda", dialCode: "+1441" },
  { flag: "🇧🇹", label: "Bhutan", dialCode: "+975" },
  { flag: "🇧🇴", label: "Bolivia", dialCode: "+591" },
  { flag: "🇧🇦", label: "Bosnia and Herzegovina", dialCode: "+387" },
  { flag: "🇧🇼", label: "Botswana", dialCode: "+267" },
  { flag: "🇧🇷", label: "Brazil", dialCode: "+55" },
  { flag: "🇻🇬", label: "British Virgin Islands", dialCode: "+1284" },
  { flag: "🇧🇳", label: "Brunei", dialCode: "+673" },
  { flag: "🇧🇬", label: "Bulgaria", dialCode: "+359" },
  { flag: "🇧🇫", label: "Burkina Faso", dialCode: "+226" },
  { flag: "🇧🇮", label: "Burundi", dialCode: "+257" },
  { flag: "🇰🇭", label: "Cambodia", dialCode: "+855" },
  { flag: "🇨🇲", label: "Cameroon", dialCode: "+237" },
  { flag: "🇨🇦", label: "Canada", dialCode: "+1" },
  { flag: "🇨🇻", label: "Cape Verde", dialCode: "+238" },
  { flag: "🇰🇾", label: "Cayman Islands", dialCode: "+1345" },
  { flag: "🇨🇫", label: "Central African Republic", dialCode: "+236" },
  { flag: "🇹🇩", label: "Chad", dialCode: "+235" },
  { flag: "🇨🇱", label: "Chile", dialCode: "+56" },
  { flag: "🇨🇳", label: "China", dialCode: "+86" },
  { flag: "🇨🇴", label: "Colombia", dialCode: "+57" },
  { flag: "🇰🇲", label: "Comoros", dialCode: "+269" },
  { flag: "🇨🇬", label: "Congo", dialCode: "+242" },
  { flag: "🇨🇩", label: "Congo, Democratic Republic", dialCode: "+243" },
  { flag: "🇨🇰", label: "Cook Islands", dialCode: "+682" },
  { flag: "🇨🇷", label: "Costa Rica", dialCode: "+506" },
  { flag: "🇭🇷", label: "Croatia", dialCode: "+385" },
  { flag: "🇨🇺", label: "Cuba", dialCode: "+53" },
  { flag: "🇨🇼", label: "Curacao", dialCode: "+599" },
  { flag: "🇨🇾", label: "Cyprus", dialCode: "+357" },
  { flag: "🇨🇿", label: "Czech Republic", dialCode: "+420" },
  { flag: "🇩🇰", label: "Denmark", dialCode: "+45" },
  { flag: "🇩🇯", label: "Djibouti", dialCode: "+253" },
  { flag: "🇩🇲", label: "Dominica", dialCode: "+1767" },
  { flag: "🇩🇴", label: "Dominican Republic", dialCode: "+1809" },
  { flag: "🇪🇨", label: "Ecuador", dialCode: "+593" },
  { flag: "🇪🇬", label: "Egypt", dialCode: "+20" },
  { flag: "🇸🇻", label: "El Salvador", dialCode: "+503" },
  { flag: "🇬🇶", label: "Equatorial Guinea", dialCode: "+240" },
  { flag: "🇪🇷", label: "Eritrea", dialCode: "+291" },
  { flag: "🇪🇪", label: "Estonia", dialCode: "+372" },
  { flag: "🇸🇿", label: "Eswatini", dialCode: "+268" },
  { flag: "🇪🇹", label: "Ethiopia", dialCode: "+251" },
  { flag: "🇫🇰", label: "Falkland Islands", dialCode: "+500" },
  { flag: "🇫🇴", label: "Faroe Islands", dialCode: "+298" },
  { flag: "🇫🇯", label: "Fiji", dialCode: "+679" },
  { flag: "🇫🇮", label: "Finland", dialCode: "+358" },
  { flag: "🇫🇷", label: "France", dialCode: "+33" },
  { flag: "🇬🇫", label: "French Guiana", dialCode: "+594" },
  { flag: "🇵🇫", label: "French Polynesia", dialCode: "+689" },
  { flag: "🇬🇦", label: "Gabon", dialCode: "+241" },
  { flag: "🇬🇲", label: "Gambia", dialCode: "+220" },
  { flag: "🇬🇪", label: "Georgia", dialCode: "+995" },
  { flag: "🇩🇪", label: "Germany", dialCode: "+49" },
  { flag: "🇬🇭", label: "Ghana", dialCode: "+233" },
  { flag: "🇬🇮", label: "Gibraltar", dialCode: "+350" },
  { flag: "🇬🇷", label: "Greece", dialCode: "+30" },
  { flag: "🇬🇱", label: "Greenland", dialCode: "+299" },
  { flag: "🇬🇩", label: "Grenada", dialCode: "+1473" },
  { flag: "🇬🇵", label: "Guadeloupe", dialCode: "+590" },
  { flag: "🇬🇺", label: "Guam", dialCode: "+1671" },
  { flag: "🇬🇹", label: "Guatemala", dialCode: "+502" },
  { flag: "🇬🇬", label: "Guernsey", dialCode: "+44" },
  { flag: "🇬🇳", label: "Guinea", dialCode: "+224" },
  { flag: "🇬🇼", label: "Guinea-Bissau", dialCode: "+245" },
  { flag: "🇬🇾", label: "Guyana", dialCode: "+592" },
  { flag: "🇭🇹", label: "Haiti", dialCode: "+509" },
  { flag: "🇭🇳", label: "Honduras", dialCode: "+504" },
  { flag: "🇭🇰", label: "Hong Kong", dialCode: "+852" },
  { flag: "🇭🇺", label: "Hungary", dialCode: "+36" },
  { flag: "🇮🇸", label: "Iceland", dialCode: "+354" },
  { flag: "🇮🇳", label: "India", dialCode: "+91" },
  { flag: "🇮🇩", label: "Indonesia", dialCode: "+62" },
  { flag: "🇮🇷", label: "Iran", dialCode: "+98" },
  { flag: "🇮🇶", label: "Iraq", dialCode: "+964" },
  { flag: "🇮🇪", label: "Ireland", dialCode: "+353" },
  { flag: "🇮🇲", label: "Isle of Man", dialCode: "+44" },
  { flag: "🇮🇱", label: "Israel", dialCode: "+972" },
  { flag: "🇮🇹", label: "Italy", dialCode: "+39" },
  { flag: "🇨🇮", label: "Ivory Coast", dialCode: "+225" },
  { flag: "🇯🇲", label: "Jamaica", dialCode: "+1876" },
  { flag: "🇯🇵", label: "Japan", dialCode: "+81" },
  { flag: "🇯🇪", label: "Jersey", dialCode: "+44" },
  { flag: "🇯🇴", label: "Jordan", dialCode: "+962" },
  { flag: "🇰🇿", label: "Kazakhstan", dialCode: "+7" },
  { flag: "🇰🇪", label: "Kenya", dialCode: "+254" },
  { flag: "🇰🇮", label: "Kiribati", dialCode: "+686" },
  { flag: "🇽🇰", label: "Kosovo", dialCode: "+383" },
  { flag: "🇰🇼", label: "Kuwait", dialCode: "+965" },
  { flag: "🇰🇬", label: "Kyrgyzstan", dialCode: "+996" },
  { flag: "🇱🇦", label: "Laos", dialCode: "+856" },
  { flag: "🇱🇻", label: "Latvia", dialCode: "+371" },
  { flag: "🇱🇧", label: "Lebanon", dialCode: "+961" },
  { flag: "🇱🇸", label: "Lesotho", dialCode: "+266" },
  { flag: "🇱🇷", label: "Liberia", dialCode: "+231" },
  { flag: "🇱🇾", label: "Libya", dialCode: "+218" },
  { flag: "🇱🇮", label: "Liechtenstein", dialCode: "+423" },
  { flag: "🇱🇹", label: "Lithuania", dialCode: "+370" },
  { flag: "🇱🇺", label: "Luxembourg", dialCode: "+352" },
  { flag: "🇲🇴", label: "Macau", dialCode: "+853" },
  { flag: "🇲🇬", label: "Madagascar", dialCode: "+261" },
  { flag: "🇲🇼", label: "Malawi", dialCode: "+265" },
  { flag: "🇲🇾", label: "Malaysia", dialCode: "+60" },
  { flag: "🇲🇻", label: "Maldives", dialCode: "+960" },
  { flag: "🇲🇱", label: "Mali", dialCode: "+223" },
  { flag: "🇲🇹", label: "Malta", dialCode: "+356" },
  { flag: "🇲🇭", label: "Marshall Islands", dialCode: "+692" },
  { flag: "🇲🇶", label: "Martinique", dialCode: "+596" },
  { flag: "🇲🇷", label: "Mauritania", dialCode: "+222" },
  { flag: "🇲🇺", label: "Mauritius", dialCode: "+230" },
  { flag: "🇾🇹", label: "Mayotte", dialCode: "+262" },
  { flag: "🇲🇽", label: "Mexico", dialCode: "+52" },
  { flag: "🇫🇲", label: "Micronesia", dialCode: "+691" },
  { flag: "🇲🇩", label: "Moldova", dialCode: "+373" },
  { flag: "🇲🇨", label: "Monaco", dialCode: "+377" },
  { flag: "🇲🇳", label: "Mongolia", dialCode: "+976" },
  { flag: "🇲🇪", label: "Montenegro", dialCode: "+382" },
  { flag: "🇲🇸", label: "Montserrat", dialCode: "+1664" },
  { flag: "🇲🇦", label: "Morocco", dialCode: "+212" },
  { flag: "🇲🇿", label: "Mozambique", dialCode: "+258" },
  { flag: "🇲🇲", label: "Myanmar", dialCode: "+95" },
  { flag: "🇳🇦", label: "Namibia", dialCode: "+264" },
  { flag: "🇳🇷", label: "Nauru", dialCode: "+674" },
  { flag: "🇳🇵", label: "Nepal", dialCode: "+977" },
  { flag: "🇳🇱", label: "Netherlands", dialCode: "+31" },
  { flag: "🇳🇨", label: "New Caledonia", dialCode: "+687" },
  { flag: "🇳🇿", label: "New Zealand", dialCode: "+64" },
  { flag: "🇳🇮", label: "Nicaragua", dialCode: "+505" },
  { flag: "🇳🇪", label: "Niger", dialCode: "+227" },
  { flag: "🇳🇬", label: "Nigeria", dialCode: "+234" },
  { flag: "🇳🇺", label: "Niue", dialCode: "+683" },
  { flag: "🇰🇵", label: "North Korea", dialCode: "+850" },
  { flag: "🇲🇰", label: "North Macedonia", dialCode: "+389" },
  { flag: "🇲🇵", label: "Northern Mariana Islands", dialCode: "+1670" },
  { flag: "🇳🇴", label: "Norway", dialCode: "+47" },
  { flag: "🇴🇲", label: "Oman", dialCode: "+968" },
  { flag: "🇵🇰", label: "Pakistan", dialCode: "+92" },
  { flag: "🇵🇼", label: "Palau", dialCode: "+680" },
  { flag: "🇵🇸", label: "Palestine", dialCode: "+970" },
  { flag: "🇵🇦", label: "Panama", dialCode: "+507" },
  { flag: "🇵🇬", label: "Papua New Guinea", dialCode: "+675" },
  { flag: "🇵🇾", label: "Paraguay", dialCode: "+595" },
  { flag: "🇵🇪", label: "Peru", dialCode: "+51" },
  { flag: "🇵🇭", label: "Philippines", dialCode: "+63" },
  { flag: "🇵🇱", label: "Poland", dialCode: "+48" },
  { flag: "🇵🇹", label: "Portugal", dialCode: "+351" },
  { flag: "🇵🇷", label: "Puerto Rico", dialCode: "+1787" },
  { flag: "🇶🇦", label: "Qatar", dialCode: "+974" },
  { flag: "🇷🇪", label: "Reunion", dialCode: "+262" },
  { flag: "🇷🇴", label: "Romania", dialCode: "+40" },
  { flag: "🇷🇺", label: "Russia", dialCode: "+7" },
  { flag: "🇷🇼", label: "Rwanda", dialCode: "+250" },
  { flag: "🇧🇱", label: "Saint Barthelemy", dialCode: "+590" },
  { flag: "🇸🇭", label: "Saint Helena", dialCode: "+290" },
  { flag: "🇰🇳", label: "Saint Kitts and Nevis", dialCode: "+1869" },
  { flag: "🇱🇨", label: "Saint Lucia", dialCode: "+1758" },
  { flag: "🇲🇫", label: "Saint Martin", dialCode: "+590" },
  { flag: "🇵🇲", label: "Saint Pierre and Miquelon", dialCode: "+508" },
  { flag: "🇻🇨", label: "Saint Vincent and the Grenadines", dialCode: "+1784" },
  { flag: "🇼🇸", label: "Samoa", dialCode: "+685" },
  { flag: "🇸🇲", label: "San Marino", dialCode: "+378" },
  { flag: "🇸🇹", label: "Sao Tome and Principe", dialCode: "+239" },
  { flag: "🇸🇦", label: "Saudi Arabia", dialCode: "+966" },
  { flag: "🇸🇳", label: "Senegal", dialCode: "+221" },
  { flag: "🇷🇸", label: "Serbia", dialCode: "+381" },
  { flag: "🇸🇨", label: "Seychelles", dialCode: "+248" },
  { flag: "🇸🇱", label: "Sierra Leone", dialCode: "+232" },
  { flag: "🇸🇬", label: "Singapore", dialCode: "+65" },
  { flag: "🇸🇽", label: "Sint Maarten", dialCode: "+1721" },
  { flag: "🇸🇰", label: "Slovakia", dialCode: "+421" },
  { flag: "🇸🇮", label: "Slovenia", dialCode: "+386" },
  { flag: "🇸🇧", label: "Solomon Islands", dialCode: "+677" },
  { flag: "🇸🇴", label: "Somalia", dialCode: "+252" },
  { flag: "🇿🇦", label: "South Africa", dialCode: "+27" },
  { flag: "🇰🇷", label: "South Korea", dialCode: "+82" },
  { flag: "🇸🇸", label: "South Sudan", dialCode: "+211" },
  { flag: "🇪🇸", label: "Spain", dialCode: "+34" },
  { flag: "🇱🇰", label: "Sri Lanka", dialCode: "+94" },
  { flag: "🇸🇩", label: "Sudan", dialCode: "+249" },
  { flag: "🇸🇷", label: "Suriname", dialCode: "+597" },
  { flag: "🇸🇪", label: "Sweden", dialCode: "+46" },
  { flag: "🇨🇭", label: "Switzerland", dialCode: "+41" },
  { flag: "🇸🇾", label: "Syria", dialCode: "+963" },
  { flag: "🇹🇼", label: "Taiwan", dialCode: "+886" },
  { flag: "🇹🇯", label: "Tajikistan", dialCode: "+992" },
  { flag: "🇹🇿", label: "Tanzania", dialCode: "+255" },
  { flag: "🇹🇭", label: "Thailand", dialCode: "+66" },
  { flag: "🇹🇱", label: "Timor-Leste", dialCode: "+670" },
  { flag: "🇹🇬", label: "Togo", dialCode: "+228" },
  { flag: "🇹🇰", label: "Tokelau", dialCode: "+690" },
  { flag: "🇹🇴", label: "Tonga", dialCode: "+676" },
  { flag: "🇹🇹", label: "Trinidad and Tobago", dialCode: "+1868" },
  { flag: "🇹🇳", label: "Tunisia", dialCode: "+216" },
  { flag: "🇹🇷", label: "Turkey", dialCode: "+90" },
  { flag: "🇹🇲", label: "Turkmenistan", dialCode: "+993" },
  { flag: "🇹🇨", label: "Turks and Caicos Islands", dialCode: "+1649" },
  { flag: "🇹🇻", label: "Tuvalu", dialCode: "+688" },
  { flag: "🇺🇬", label: "Uganda", dialCode: "+256" },
  { flag: "🇺🇦", label: "Ukraine", dialCode: "+380" },
  { flag: "🇬🇧", label: "United Kingdom", dialCode: "+44" },
  { flag: "🇺🇸", label: "United States", dialCode: "+1" },
  { flag: "🇺🇾", label: "Uruguay", dialCode: "+598" },
  { flag: "🇺🇿", label: "Uzbekistan", dialCode: "+998" },
  { flag: "🇻🇺", label: "Vanuatu", dialCode: "+678" },
  { flag: "🇻🇦", label: "Vatican City", dialCode: "+39" },
  { flag: "🇻🇪", label: "Venezuela", dialCode: "+58" },
  { flag: "🇻🇳", label: "Vietnam", dialCode: "+84" },
  { flag: "🇻🇮", label: "Virgin Islands, US", dialCode: "+1340" },
  { flag: "🇼🇫", label: "Wallis and Futuna", dialCode: "+681" },
  { flag: "🇾🇪", label: "Yemen", dialCode: "+967" },
  { flag: "🇿🇲", label: "Zambia", dialCode: "+260" },
  { flag: "🇿🇼", label: "Zimbabwe", dialCode: "+263" }
];
